"""
data_real_seeded/build_real_seeded_data.py

Builds a longer (2021-01-01 to 2026-08-31, matching data_synthetic_backup's
date range) backtest dataset that's grounded in real data wherever real
data actually exists, rather than data_synthetic_backup's fully
hand-tuned assumptions.

Demand:
  - Espresso Beans (Arabica), Whole Milk, Sugar are the only 3 of our 6
    showcase SKUs that also appear as real, recipe-linked ingredients in
    the 6-day real Kaggle order data (kaggle_raw/). Daily demand here is
    generated by sampling around the REAL observed mean and standard
    deviation of daily consumption over those 6 real days (via
    build_real_data.py's own ingredient-demand extraction, reused
    directly), shaped by generate_data.py's weekly/seasonal multiplier
    functions (also reused directly). 6 real days cannot reveal a real
    weekly or seasonal pattern -- so the SHAPE is still an assumption,
    but the LEVEL and VARIABILITY are real numbers, not invented ones.
  - Oat Milk, Paper Cups (12oz) never appeared in the real shop's order
    data at all -- there is no real consumption number to seed them
    with, so their demand is copied unchanged from data_synthetic_backup/.
  - Vanilla Syrup has a real ingredient PRICE in kaggle_raw/ingredients.csv
    but zero real demand (no recipe in the real data uses it), so its
    demand is also copied unchanged from data_synthetic_backup/.

Starting supplier price:
  - For the 3 real-seeded-demand SKUs plus Vanilla Syrup, anchored to the
    REAL per-unit ingredient cost in kaggle_raw/ingredients.csv (not the
    arbitrary numbers in generate_data.py).
  - Oat Milk and Paper Cups keep generate_data.py's original prices --
    no real price or demand exists for either.

This script does NOT apply the real market-price trend over time --
that happens at query time in backtest/state.py's
build_effective_supplier_price(), using market_data/market_trends.csv,
so every price still respects the no-lookahead guardrail the same way
build_market_trend_signal() does. suppliers.csv here only holds each
supplier's price AS OF the dataset's start date (2021-01-01); state.py
scales it up/down from there.

Run: python data_real_seeded/build_real_seeded_data.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from build_real_data import DISPLAY_SCALE, build_ingredient_demand, clean_orders, load_raw  # noqa: E402
from generate_data import SUPPLIERS as SYNTHETIC_SUPPLIERS  # noqa: E402
from generate_data import seasonal_multiplier, weekly_multiplier  # noqa: E402

RNG_SEED = 42
rng = np.random.default_rng(RNG_SEED)

OUT_DIR = Path(__file__).parent
SYNTH_DIR = ROOT / "data_synthetic_backup"

START_DATE = "2021-01-01"
END_DATE = "2026-08-31"
DATES = pd.date_range(START_DATE, END_DATE, freq="D")

ANNUAL_HOLDING_RATE = 0.20  # same heuristic build_real_data.py uses
FLAT_SAFETY_STOCK_DAYS = 5

# our showcase sku name -> real ingredient name in kaggle_raw/ingredients.csv
REAL_DEMAND_SKUS = {
    "Espresso Beans (Arabica)": "Espresso beans",
    "Whole Milk": "Whole Milk",
    "Sugar": "Sugar",
}
# has a real ingredient PRICE but no real recipe-linked demand (unused in
# any real recipe) -- price-anchor it anyway, demand stays synthetic
REAL_PRICE_ONLY_SKUS = {"Vanilla Syrup": "Vanilla syrup"}
SYNTHETIC_ONLY_SKUS = ["Oat Milk", "Paper Cups (12oz)"]

# weekly/seasonal SHAPE is an assumption -- 6 real days can't reveal a
# real pattern -- so reuse generate_data.py's own typical amplitude range
WEEKLY_AMP, ANNUAL_AMP = 0.20, 0.10


def real_ingredient_stats():
    """Real per-ingredient daily-consumption mean/std (from the 6 real
    order days) and real per-unit price, for every sku we can seed from
    kaggle_raw/ at all (demand-seeded or price-only)."""
    ingredients, inventory, items, orders, recipe = load_raw()

    ing_scale, ing_display_unit = {}, {}
    for _, r in ingredients.iterrows():
        factor, label = DISPLAY_SCALE[r["ing_meas"]]
        ing_scale[r["ing_id"]] = factor
        ing_display_unit[r["ing_id"]] = label

    orders_clean, _, _ = clean_orders(orders, items)
    daily = build_ingredient_demand(orders_clean, items, recipe, ing_scale)

    ing_name_to_id = {r["ing_name"]: r["ing_id"] for _, r in ingredients.iterrows()}
    ing = ingredients.set_index("ing_id")

    stats = {}
    for sku, real_name in {**REAL_DEMAND_SKUS, **REAL_PRICE_ONLY_SKUS}.items():
        ing_id = ing_name_to_id[real_name]
        scale = ing_scale[ing_id]
        unit_price = float(ing.loc[ing_id, "ing_price"]) / (float(ing.loc[ing_id, "ing_weight"]) * scale)

        vals = daily.loc[daily["ing_id"] == ing_id, "units_sold"].to_numpy()
        has_real_demand = sku in REAL_DEMAND_SKUS and len(vals) > 0
        stats[sku] = {
            "unit": ing_display_unit[ing_id],
            "unit_price": unit_price,
            "real_mean_daily": float(vals.mean()) if has_real_demand else None,
            "real_std_daily": float(vals.std()) if has_real_demand and len(vals) > 1 else None,
            "real_n_obs": len(vals) if has_real_demand else 0,
        }
    return stats


def generate_real_seeded_demand(stats: dict) -> pd.DataFrame:
    records = []
    for sku, s in stats.items():
        if s["real_mean_daily"] is None:
            continue  # price-only sku (Vanilla Syrup) -- demand handled separately
        mean = s["real_mean_daily"]
        std = s["real_std_daily"] or mean * 0.15
        cv = std / mean if mean > 0 else 0.15
        on_hand = mean * FLAT_SAFETY_STOCK_DAYS * 2

        for i, d in enumerate(DATES):
            seasonal = seasonal_multiplier(d.dayofyear, ANNUAL_AMP)
            weekly = weekly_multiplier(d.weekday(), WEEKLY_AMP)
            noise = rng.normal(1.0, cv)
            demand = max(0.0, mean * seasonal * weekly * noise)
            units_sold = round(demand)
            on_hand -= units_sold
            stockout = on_hand < 0
            if stockout:
                on_hand = 0
            reorder_point = mean * FLAT_SAFETY_STOCK_DAYS
            if on_hand < reorder_point and i % 3 == 0:
                on_hand += mean * FLAT_SAFETY_STOCK_DAYS * 2.5
            records.append({
                "date": d.date().isoformat(), "sku": sku,
                "units_sold": units_sold, "on_hand": round(on_hand, 1),
                "stockout_flag": stockout,
            })
    return pd.DataFrame(records)


def build_suppliers(stats: dict) -> pd.DataFrame:
    rows = []
    price_anchored_skus = {**REAL_DEMAND_SKUS, **REAL_PRICE_ONLY_SKUS}
    for sku, sup_list in SYNTHETIC_SUPPLIERS.items():
        for s in sup_list:
            s = dict(s)
            if sku in price_anchored_skus:
                # same +/-15% cross-supplier spread build_real_data.py used,
                # but anchored to the REAL unit price instead of an
                # arbitrary synthetic one
                price_mult = rng.uniform(0.88, 1.15)
                s["price"] = round(stats[sku]["unit_price"] * price_mult, 3)
            rows.append({"sku": sku, **s})
    return pd.DataFrame(rows)


def build_skus(stats: dict) -> pd.DataFrame:
    synth_skus = pd.read_csv(SYNTH_DIR / "skus.csv").set_index("sku")
    rows = []
    price_anchored_skus = {**REAL_DEMAND_SKUS, **REAL_PRICE_ONLY_SKUS}
    for sku, base in synth_skus.iterrows():
        unit = stats[sku]["unit"] if sku in price_anchored_skus else base["unit"]
        holding_cost = (
            round(stats[sku]["unit_price"] * ANNUAL_HOLDING_RATE / 365, 5)
            if sku in price_anchored_skus else base["holding_cost_per_unit_day"]
        )
        rows.append({
            "sku": sku,
            "unit": unit,
            "holding_cost_per_unit_day": holding_cost,
            "ordering_cost": base["ordering_cost"],
            "safety_stock_days": base["safety_stock_days"],
        })
    return pd.DataFrame(rows)


def main():
    stats = real_ingredient_stats()

    real_seeded_demand = generate_real_seeded_demand(stats)
    synthetic_demand = pd.read_csv(SYNTH_DIR / "daily_demand.csv")
    synthetic_only = synthetic_demand[synthetic_demand["sku"].isin(
        SYNTHETIC_ONLY_SKUS + list(REAL_PRICE_ONLY_SKUS.keys())
    )]
    demand_out = pd.concat([real_seeded_demand, synthetic_only], ignore_index=True)
    demand_out.to_csv(OUT_DIR / "daily_demand.csv", index=False)

    build_skus(stats).to_csv(OUT_DIR / "skus.csv", index=False)
    build_suppliers(stats).to_csv(OUT_DIR / "suppliers.csv", index=False)

    print("=" * 70)
    print(f"[done] wrote data_real_seeded/{{daily_demand,skus,suppliers}}.csv")
    for sku, s in stats.items():
        kind = "REAL demand + REAL price anchor" if s["real_mean_daily"] is not None else "REAL price anchor only (no real demand)"
        print(f"  {sku:28s} {kind}  (n={s['real_n_obs']} real obs, unit_price=${s['unit_price']:.3f}/{s['unit']})")
    for sku in SYNTHETIC_ONLY_SKUS:
        print(f"  {sku:28s} fully synthetic (no real demand or price data exists)")
    print("=" * 70)


if __name__ == "__main__":
    main()
